package com.nearchat.app;

import android.Manifest;
import android.annotation.SuppressLint;
import android.bluetooth.*;
import android.bluetooth.le.*;
import android.content.Context;
import android.content.pm.PackageManager;
import android.os.Handler;
import android.os.Looper;
import android.os.ParcelUuid;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

public class BleChatManager {
    public static final UUID SERVICE_UUID = UUID.fromString("0000feed-0000-1000-8000-00805f9b34fb");
    public static final UUID RX_UUID = UUID.fromString("0000feed-0001-1000-8000-00805f9b34fb");
    public static final UUID TX_UUID = UUID.fromString("0000feed-0002-1000-8000-00805f9b34fb");
    private static final UUID CCCD = UUID.fromString("00002902-0000-1000-8000-00805f9b34fb");
    public interface Listener { void onStatus(String s); void onDevice(BluetoothDevice d); void onMessage(String msg, boolean mine); void onError(String e); }
    private final Context ctx; private final Listener listener; private final BluetoothAdapter adapter; private BluetoothLeScanner scanner; private BluetoothLeAdvertiser advertiser; private BluetoothGatt gatt; private BluetoothGattServer server; private BluetoothGattCharacteristic rx, tx; private boolean scanning;
    private final Handler main = new Handler(Looper.getMainLooper()); private final Set<BluetoothDevice> peers = Collections.newSetFromMap(new ConcurrentHashMap<>()); private final Map<String, Assembly> incoming = new ConcurrentHashMap<>(); private final Queue<byte[]> writeQueue = new ArrayDeque<>(); private boolean writing; private int msgId=0;
    public BleChatManager(Context c,Listener l){ctx=c.getApplicationContext();listener=l;BluetoothManager bm=(BluetoothManager)ctx.getSystemService(Context.BLUETOOTH_SERVICE);adapter=bm.getAdapter();}
    private boolean p(String x){return ctx.checkSelfPermission(x)==PackageManager.PERMISSION_GRANTED;} private boolean ready(){return adapter!=null&&adapter.isEnabled();}
    @SuppressLint("MissingPermission") public void start(){if(!ready()){listener.onError("Bluetooth is off or unavailable");return;}startServer();startAdvertising();}
    @SuppressLint("MissingPermission") public void scan(){if(!ready()||!p(Manifest.permission.BLUETOOTH_SCAN)){listener.onError("Bluetooth scan permission is required");return;}if(scanning)return;scanner=adapter.getBluetoothLeScanner();peers.clear();scanning=true;listener.onStatus("Scanning…");scanner.startScan(Collections.singletonList(new ScanFilter.Builder().setServiceUuid(new ParcelUuid(SERVICE_UUID)).build()),new ScanSettings.Builder().setScanMode(ScanSettings.SCAN_MODE_LOW_LATENCY).build(),scanCallback);main.postDelayed(this::stopScan,10000);}
    @SuppressLint("MissingPermission") public void stopScan(){if(!scanning)return;scanning=false;if(scanner!=null)scanner.stopScan(scanCallback);listener.onStatus(gatt==null?"Ready":"Connected");}
    private final ScanCallback scanCallback=new ScanCallback(){@Override public void onScanResult(int type,ScanResult r){BluetoothDevice d=r.getDevice();if(d!=null&&peers.add(d))listener.onDevice(d);}};
    @SuppressLint("MissingPermission") public void connect(BluetoothDevice d){stopScan();if(!p(Manifest.permission.BLUETOOTH_CONNECT)){listener.onError("Bluetooth connect permission is required");return;}listener.onStatus("Connecting to "+safeName(d));if(gatt!=null){gatt.close();gatt=null;}gatt=d.connectGatt(ctx,false,gattCallback,BluetoothDevice.TRANSPORT_LE);}
    private String safeName(BluetoothDevice d){try{return d.getName()!=null?d.getName():d.getAddress();}catch(Exception e){return "device";}}
    private final BluetoothGattCallback gattCallback=new BluetoothGattCallback(){
        @Override public void onConnectionStateChange(BluetoothGatt g,int status,int state){if(state==BluetoothProfile.STATE_CONNECTED){listener.onStatus("Connected to "+safeName(g.getDevice()));g.requestMtu(247);g.discoverServices();}else if(state==BluetoothProfile.STATE_DISCONNECTED){listener.onStatus("Disconnected");closeGatt();}}
        @Override public void onMtuChanged(BluetoothGatt g,int mtu,int status){g.discoverServices();}
        @Override public void onServicesDiscovered(BluetoothGatt g,int status){BluetoothGattService s=g.getService(SERVICE_UUID);if(s==null){listener.onError("NearChat service not found");return;}tx=s.getCharacteristic(TX_UUID);rx=s.getCharacteristic(RX_UUID);if(tx==null||rx==null){listener.onError("Chat characteristics not found");return;}if(p(Manifest.permission.BLUETOOTH_CONNECT)){g.setCharacteristicNotification(tx,true);BluetoothGattDescriptor d=tx.getDescriptor(CCCD);if(d!=null){d.setValue(BluetoothGattDescriptor.ENABLE_NOTIFICATION_VALUE);g.writeDescriptor(d);}}}
        @Override public void onDescriptorWrite(BluetoothGatt g,BluetoothGattDescriptor d,int status){if(d.getUuid().equals(CCCD))listener.onStatus("Connected — chat ready");}
        @Override public void onCharacteristicChanged(BluetoothGatt g,BluetoothGattCharacteristic c){if(TX_UUID.equals(c.getUuid()))handleChunk(g.getDevice().getAddress(),c.getValue(),false);}
        @Override public void onCharacteristicWrite(BluetoothGatt g,BluetoothGattCharacteristic c,int status){synchronized(writeQueue){writing=false;writeNext();}}
    };
    @SuppressLint("MissingPermission") public void send(String text){if(text==null||text.trim().isEmpty())return;byte[] all=text.getBytes(StandardCharsets.UTF_8);if(gatt==null||rx==null){listener.onError("Connect to a NearChat device first");return;}int payload=20,id=(++msgId)&255,total=(int)Math.ceil(all.length/(double)(payload-3));if(total>255){listener.onError("Message is too long");return;}for(int i=0;i<total;i++){int a=i*(payload-3),b=Math.min(all.length,a+payload-3);byte[] part=new byte[3+b-a];part[0]=(byte)id;part[1]=(byte)total;part[2]=(byte)i;System.arraycopy(all,a,part,3,b-a);synchronized(writeQueue){writeQueue.add(part);}}synchronized(writeQueue){writeNext();}listener.onMessage(text,true);}
    @SuppressLint("MissingPermission") private void writeNext(){if(writing||writeQueue.isEmpty()||gatt==null||rx==null)return;byte[] data=writeQueue.peek();rx.setWriteType(BluetoothGattCharacteristic.WRITE_TYPE_DEFAULT);rx.setValue(data);writing=true;if(!gatt.writeCharacteristic(rx)){writing=false;writeQueue.poll();writeNext();}else writeQueue.poll();}
    private void handleChunk(String peer,byte[] p,boolean mine){if(p==null||p.length<3)return;int id=p[0]&255,total=p[1]&255,index=p[2]&255;String key=peer+":"+id;Assembly a=incoming.computeIfAbsent(key,k->new Assembly(total));a.parts.put(index,Arrays.copyOfRange(p,3,p.length));if(a.parts.size()==a.total){int n=0;for(byte[] x:a.parts.values())n+=x.length;byte[] all=new byte[n];int pos=0;for(int i=0;i<a.total;i++){byte[] x=a.parts.get(i);if(x==null)return;System.arraycopy(x,0,all,pos,x.length);pos+=x.length;}incoming.remove(key);listener.onMessage(new String(all,StandardCharsets.UTF_8),mine);}}
    private static class Assembly{final int total;final Map<Integer,byte[]> parts=new HashMap<>();Assembly(int t){total=t;}}
    @SuppressLint("MissingPermission") private void startServer(){if(!p(Manifest.permission.BLUETOOTH_ADVERTISE)||!p(Manifest.permission.BLUETOOTH_CONNECT)){listener.onError("Bluetooth advertise/connect permissions are required");return;}BluetoothManager bm=(BluetoothManager)ctx.getSystemService(Context.BLUETOOTH_SERVICE);if(server!=null)server.close();server=bm.openGattServer(ctx,gattServerCallback);BluetoothGattService s=new BluetoothGattService(SERVICE_UUID,BluetoothGattService.SERVICE_TYPE_PRIMARY);rx=new BluetoothGattCharacteristic(RX_UUID,BluetoothGattCharacteristic.PROPERTY_WRITE|BluetoothGattCharacteristic.PROPERTY_WRITE_NO_RESPONSE,BluetoothGattCharacteristic.PERMISSION_WRITE);tx=new BluetoothGattCharacteristic(TX_UUID,BluetoothGattCharacteristic.PROPERTY_NOTIFY,BluetoothGattCharacteristic.PERMISSION_READ);tx.addDescriptor(new BluetoothGattDescriptor(CCCD,BluetoothGattDescriptor.PERMISSION_READ|BluetoothGattDescriptor.PERMISSION_WRITE));s.addCharacteristic(rx);s.addCharacteristic(tx);server.addService(s);}
    private final BluetoothGattServerCallback gattServerCallback=new BluetoothGattServerCallback(){@Override public void onConnectionStateChange(BluetoothDevice d,int status,int state){if(state==BluetoothProfile.STATE_CONNECTED)listener.onStatus("Peer connected: "+safeName(d));else if(state==BluetoothProfile.STATE_DISCONNECTED)listener.onStatus(gatt==null?"Ready":"Connected");}@Override public void onDescriptorWriteRequest(BluetoothDevice d,int requestId,BluetoothGattDescriptor desc,boolean prepared,boolean responseNeeded,int offset,byte[] value){if(responseNeeded)server.sendResponse(d,requestId,BluetoothGatt.GATT_SUCCESS,0,null);}@Override public void onCharacteristicWriteRequest(BluetoothDevice d,int requestId,BluetoothGattCharacteristic c,boolean prepared,boolean responseNeeded,int offset,byte[] value){if(RX_UUID.equals(c.getUuid())){handleChunk(d.getAddress(),value,false);if(responseNeeded)server.sendResponse(d,requestId,BluetoothGatt.GATT_SUCCESS,0,null);broadcast(value);}}};
    @SuppressLint("MissingPermission") private void broadcast(byte[] value){if(server==null||tx==null)return;for(BluetoothDevice d:((BluetoothManager)ctx.getSystemService(Context.BLUETOOTH_SERVICE)).getConnectedDevices(BluetoothProfile.GATT_SERVER)){tx.setValue(value);server.notifyCharacteristicChanged(d,tx,false);}}
    @SuppressLint("MissingPermission") private void startAdvertising(){if(!p(Manifest.permission.BLUETOOTH_ADVERTISE))return;advertiser=adapter.getBluetoothLeAdvertiser();if(advertiser==null){listener.onError("BLE advertising is not supported");return;}AdvertiseSettings settings=new AdvertiseSettings.Builder().setAdvertiseMode(AdvertiseSettings.ADVERTISE_MODE_LOW_LATENCY).setTxPowerLevel(AdvertiseSettings.ADVERTISE_TX_POWER_MEDIUM).setConnectable(true).build();AdvertiseData data=new AdvertiseData.Builder().addServiceUuid(new ParcelUuid(SERVICE_UUID)).setIncludeDeviceName(false).build();advertiser.startAdvertising(settings,data,advertiseCallback);}
    private final AdvertiseCallback advertiseCallback=new AdvertiseCallback(){@Override public void onStartSuccess(AdvertiseSettings s){listener.onStatus("Ready — advertising for nearby chat");}@Override public void onStartFailure(int e){listener.onError("BLE advertising failed: "+e);}};
    @SuppressLint("MissingPermission") public void stop(){stopScan();if(advertiser!=null)advertiser.stopAdvertising(advertiseCallback);if(server!=null)server.close();closeGatt();}
    @SuppressLint("MissingPermission") private void closeGatt(){if(gatt!=null){gatt.close();gatt=null;}rx=null;tx=null;}
}